
dataset:
  train_json_path: "./HNC/hnc_clean_strict_train.json"
  # train_json_path: "./HNC/hnc_train_sampled_1_percent.json"
  val_json_path: "./HNC/hnc_val_sampled_1_percent.json"
  test_json_path: "./HNC/hnc_clean_strict_test.json"
  image_folder_path: "./gqa_dataset/images/images"

training:
  model_name: "openai/clip-vit-base-patch32"
  num_epochs: 3
  learning_rate: 1.0e-5
  weight_decay: 0.05
  num_warmup_steps: 300
  mode: 'HNC'  # Choose 'HNC' or 'standard' or 'dpo'
  
  lambda_ref: 0.001
  hard_neg_weight: 1.0
  dynamic_weight: False 
  min_weight: 0
  max_weight: 3
  update_interval: 300
  num_updates: 30

  dpo_beta: 1.0
  
  checkpoint_dir: './checkpoints_HNC1'

Val:
  val_size: 300
  val_step_frequency: 1000


deepspeed:
  config:
    train_batch_size: 2048
    train_micro_batch_size_per_gpu: 256
    gradient_accumulation_steps: 2
    gradient_checkpointing: True
    gradient_clipping: 1.0
    fp16:
      enabled: false
    zero_optimization:
      stage: 2

