dataset:
  train_json_path: "/mount/studenten/team-lab-cl/data2024/w/data/thes/HNC/hnc_clean_strict_train.json"
  # train_json_path: "/mount/studenten/team-lab-cl/data2024/w/data/thes/HNC/hnc_train_sampled_1_percent.json"
  image_folder_path: "/mount/studenten/team-lab-cl/data2024/w/data/thes/gqa_dataset/images/images"

training:
  num_epochs: 5
  batch_size: 256
  learning_rate: 1.0e-4
  weight_decay: 1.0e-5
  temperature: 0.07
  hard_negative_weight: 1.5
  l2_reg_weight: 1.0e-3

deepspeed:
  config:
    train_batch_size: 256
    train_micro_batch_size_per_gpu: 16
    gradient_accumulation_steps: 2
    gradient_checkpointing: true
    gradient_clipping: 1.0
    fp16:
      enabled: true
      initial_scale_power: 16
    zero_optimization:
      stage: 2
    scheduler:
      type: "WarmupLR"
      params:
        warmup_min_lr: 0
        warmup_max_lr: 1.0e-4
        warmup_num_steps: 1000

misc:
  output_dir: "./fine_tuned_clip_1.5"
  repo_name: "HNC_clip_1.5"
  wandb_project_name: "fine-tune-hnc-clip_1.5"
