dataset:
  train_json_path: "./HNC/hnc_clean_strict_train.json"
  image_folder_path: "./gqa_dataset/images/images"

training:
  num_epochs: 5
  learning_rate: 1.0e-5
  weight_decay: 0.05
  num_warmup_steps: 50
  temperature: 0.07
  hard_negative_weight: 1.0
  dynamic_hard_negative: true 
  hard_negative_max_weight: 3.0
  l2_reg_weight: 1.0e-4
  

deepspeed:
  config:
    train_batch_size: 1024
    train_micro_batch_size_per_gpu: 64
    gradient_accumulation_steps: 4
    gradient_checkpointing: true
    gradient_clipping: 1.0
    fp16:
      enabled: true
      initial_scale_power: 12
      hysteresis: 5
      dynamic_loss_scale: true
    zero_optimization:
      stage: 2


misc:
  repo_name: "HNC_clip_D1-3"
