dataset:
  train_json_path: "./data/HNC/hnc_train_sampled_1_percent.json"
  val_json_path: "./data/HNC/hnc_val_sampled_1_percent.json"
  test_json_path: "./data/HNC/hnc_clean_strict_test.json"
  image_folder_path: "./data/gqa_dataset/images/images"

training:
  model_name: "ViT-B/32"
  num_epochs: 50
  train_size: 100000

  learning_rate: 5.0e-6
  weight_decay: 0.0001
  num_warmup_steps: 100
  mode: 'hnc_kl'  # Choose 'hnc_l2', 'hnc_kl', 'standard', 'dpo_kl', 'contrastive_dpo_kl', 'contrastive_dpo_l2'
  finetune_mode: 'full_encoder'  # Choose 'text_encoder' or 'vision_encoder' or 'full_encoder',"last_encoder"

  lambda_ref: 0.1
  hard_neg_weight: 1.0
  dynamic_weight: False 
  min_weight: 1
  max_weight: 10
  update_interval: 1000
  num_updates: 10

  dpo_beta: 0.1
  
  checkpoint_dir: './models/HNC1_01KL_F_S'

Val:
  val_size: 1000
  val_step_frequency: 1370
  split: False


deepspeed:
  config:
    train_batch_size: 128
    train_micro_batch_size_per_gpu: 32
    gradient_accumulation_steps: 2
    gradient_checkpointing: false
    gradient_clipping: 1.0
    fp16:
      enabled: false
    zero_optimization:
      stage: 2

